### ISSUE TITLE
graphmalizer doesn't read from queue

### ISSUE THREAD

**Issue by hpfast** [graphmalizer/graphmalizer-core#3]
import/api is sending stuff to the queue, but graphmalizer isn't reading them. 

When starting graphmalizer without --redis, it reports startup. with --redis, it doesn't report anything.

I've tried both master and feat/rel-nodes branch. both the same. Redis is running on port 6379, neo4j on 7474.

I have api, import, neo4j-plugin, io, ur-normalizer all installed.

Any ideas?

**Comment by wires** [comment]
Yeah, stuff is a bit messy at the moment, I'm working hard to clean this up.

The `feat/rel-nodes` branch is already merged into main, I should remove that branch.

If you start it with `--redis` the HTTP server is not started. If you start without `--redis` the http server is started.

It does batching in a very stupid way right now (I have fixed this locally, will push soon), you must specify a batch size. So when you start without `--redis` you should pass `--batchSize` 1 or HTTP request will not be processed until you've added a thousand or something...

You can try `--debug` to get (much) more output.

Try this,

`node index.js --redis --batchSize 1 --once --debug`

it should pull one msg from redis, spew debug output and stop (`--once`).

**Comment by wires** [comment]
OH! And the default queue name is wrong, try

`node index.js --redis --batchSize 1 --once --debug --queue histograph`

**Comment by hpfast** [comment]
yeah, queue count went down by 1 and there it is in neo4j!!! :rocket: 

thanks @wires, I'll await further developments.

**Comment by wires** [comment]
Whoohoo. I think it was `--queue`.. 

working on equivalences and tracking relations between them

![screen shot 2015-07-17 at 17 42 56](https://cloud.githubusercontent.com/assets/315734/8751122/8617fe90-2cab-11e5-8f31-eed64a9bb4d5.png)
